#!/usr/bin/env node
// canva-killer — render core.
// Fills a template (HTML/CSS/SVG) with a brand's tokens + the post content,
// and exports a PNG via headless Chromium. `render()` is pure enough to be
// called from both the CLI and the MCP wrapper (same logic, zero duplication).

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright-core';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const ROOT = path.resolve(__dirname, '..');
// User overlay: private/generated data (real brands, authored assets, extra templates,
// exported PNGs) lives outside the framework, in <repo>/user/canva-killer/ (gitignored). All
// brand/template/custom-icon resolution looks there first and falls back to the framework —
// this way the public repo only ships the `_TEMPLATE`/example brand, never real user data.
export const USER_ROOT = path.resolve(ROOT, '..', 'user', 'canva-killer');

const BRANDS_DIR = path.join(ROOT, 'brands');
export const USER_BRANDS_DIR = path.join(USER_ROOT, 'brands');
export const TEMPLATES_DIR = path.join(ROOT, 'templates');
export const USER_TEMPLATES_DIR = path.join(USER_ROOT, 'templates');
const ICONS_DIR = path.join(ROOT, 'node_modules', 'lucide-static', 'icons'); // ~1500 Lucide icons
const CUSTOM_ICONS_DIR = path.join(ROOT, 'assets', 'custom'); // framework's example SVGs
export const USER_CUSTOM_ICONS_DIR = path.join(USER_ROOT, 'assets', 'custom'); // SVGs generated by the svg-builder skill (user data)
const BASE_CSS = path.join(ROOT, 'partials', 'base.css'); // reset + background layers + patterns, injected via {{baseStyles}}
const DEFAULT_OUT_DIR = path.join(USER_ROOT, 'out'); // exported PNGs — user data

function isDir(d) {
  try { return fs.statSync(d).isDirectory(); } catch { return false; }
}

// Lists names (without extension) from an overlay pair (user + framework); user wins name conflicts.
function listOverlay(userDir, frameworkDir, ext) {
  const names = new Map();
  for (const dir of [frameworkDir, userDir]) {
    if (!isDir(dir)) continue;
    for (const f of fs.readdirSync(dir)) {
      if (f.endsWith(ext) && !f.startsWith('_')) names.set(f.slice(0, -ext.length), path.join(dir, f));
    }
  }
  return names;
}

// Resolves a file by name in the overlay: user first, framework underneath.
function resolveOverlay(userDir, frameworkDir, filename) {
  const userPath = path.join(userDir, filename);
  return fs.existsSync(userPath) ? userPath : path.join(frameworkDir, filename);
}

// Strips anything but word chars/hyphen from an id that becomes a path segment (brandId,
// templateId) — these arrive as free-form strings from the CLI, the MCP tool params (any AI
// agent's text), or HTTP query params, so `../../../etc/passwd` must never survive into
// path.join(). Applied once here rather than at each call site (CLI/MCP/studio) so every caller
// is covered.
const safeId = (s) => String(s || '').replace(/[^\w-]/g, '');

// Procedural noise (pat-noise) as a data URI — generated with encodeURIComponent so it doesn't break.
// Desaturated fractalNoise (feColorMatrix saturate 0) => a subtle gray texture.
const NOISE_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160"><filter id="n"><feTurbulence type="fractalNoise" baseFrequency="0.8" numOctaves="2" stitchTiles="stitch"/><feColorMatrix type="saturate" values="0"/></filter><rect width="100%" height="100%" filter="url(#n)"/></svg>`;
const NOISE_URI = `data:image/svg+xml,${encodeURIComponent(NOISE_SVG)}`;

// System Chrome — avoids downloading Playwright's binaries. Override with CHROME_PATH.
const CHROME = process.env.CHROME_PATH || '/usr/bin/google-chrome';

// Files starting with "_" are template skeletons (e.g. _TEMPLATE.json) — not real brands
// or layouts, so they're excluded from the listing.
export function listBrands() {
  return [...listOverlay(USER_BRANDS_DIR, BRANDS_DIR, '.json').keys()];
}
// Templates are brand-scoped, same overlay pattern as brands/icons: a brand only ever sees the
// framework's generic layouts (post-square, story, blog-cover, carrossel-slide) PLUS its own
// exclusive templates in user/canva-killer/templates/<brandId>/. Without a brandId, only the
// generic layouts are visible — this is the safe default, never another brand's authored work.
// (Previously this flattened EVERY brand's templates into one global namespace, so any brand
// could pick up any other brand's exclusive template — that leak is what this scoping fixes.)
export function listTemplates(brandId) {
  const id = safeId(brandId);
  const brandDir = id ? path.join(USER_TEMPLATES_DIR, id) : '';
  return [...listOverlay(brandDir, TEMPLATES_DIR, '.html').keys()];
}
export function resolveTemplatePath(templateId, brandId) {
  const id = safeId(brandId);
  const brandDir = id ? path.join(USER_TEMPLATES_DIR, id) : USER_TEMPLATES_DIR;
  return resolveOverlay(brandDir, TEMPLATES_DIR, `${safeId(templateId)}.html`);
}
export function getBrand(brandId) {
  return JSON.parse(fs.readFileSync(resolveOverlay(USER_BRANDS_DIR, BRANDS_DIR, `${safeId(brandId)}.json`), 'utf8'));
}

// base.css filled with a brand's tokens — used by the studio so the editor canvas stays
// WYSIWYG (same patterns/layers as the final render).
export function baseStylesFor(brandId) {
  return fillTemplate('{{baseStyles}}', getBrand(brandId), {});
}

// List of Lucide icon names, with an optional filter — used by the studio's icon browser.
export function listIcons(q = '', limit = 400) {
  const all = fs.readdirSync(ICONS_DIR).filter((f) => f.endsWith('.svg')).map((f) => f.replace(/\.svg$/, ''));
  const filtered = q ? all.filter((n) => n.includes(q.toLowerCase())) : all;
  return { total: filtered.length, names: filtered.slice(0, limit) };
}

// Resolves the background image slot: `data.bgimage` can be an http(s) URL or a
// local path (absolute or relative to cwd). Becomes the CSS that fills `.bg-photo` in the
// template. Empty when there's no image — the template then shows just the solid background + grid.
//
// A local image is embedded as a data URI (base64): the page comes from setContent (origin
// about:blank), so Chromium would block an external file:// for security. An http(s) URL
// is used directly (requires Chromium to have network access in the environment).
export function resolveBgStyle(bgimage) {
  if (!bgimage) return '';
  let url;
  if (/^https?:\/\//i.test(bgimage)) {
    url = bgimage;
  } else {
    const abs = path.resolve(bgimage);
    const ext = path.extname(abs).slice(1).toLowerCase();
    const mime = ext === 'jpg' ? 'jpeg' : (ext || 'png');
    url = `data:image/${mime};base64,${fs.readFileSync(abs).toString('base64')}`;
  }
  // SINGLE quotes: the template uses style="{{bgstyle}}" (double quotes); using " here would close the attribute.
  return `background-image:url('${url}');background-size:cover;background-position:center;`;
}

// Resolves {{icon:name}} -> inline SVG. "custom/xxx" looks in assets/custom/ (SVGs generated by
// the svg-builder skill); everything else comes from the Lucide library. Fixed width/height are
// stripped so the container (CSS) controls the size; stroke="currentColor" inherits color from CSS.
// `brandId` scopes "custom/xxx" lookups the same way templates are scoped: a brand-exclusive
// icon/logo in assets/custom/<brandId>/ wins over the generic (shared-by-every-brand)
// assets/custom/ tier, which in turn wins over the framework's example assets. Icons authored
// for one brand (most logos) belong in the brand tier; only genuinely reusable icons belong
// in the generic tier — same "generic vs. exclusive" split as templates/.
export function resolveIcon(name, brandId) {
  // `name` reaches here from template-embedded {{icon:...}} (regex-constrained at the call
  // site) but also directly from the studio's /api/icon-svg?name= query param (unconstrained) —
  // sanitize the actual filename segment here so neither path can traverse out of ICONS_DIR/
  // CUSTOM_ICONS_DIR (e.g. name=custom/../../../etc/passwd).
  let file;
  if (name.startsWith('custom/')) {
    const iconName = safeId(name.slice(7));
    const id = safeId(brandId);
    const brandPath = id ? path.join(USER_CUSTOM_ICONS_DIR, id, `${iconName}.svg`) : null;
    file = (brandPath && fs.existsSync(brandPath)) ? brandPath : resolveOverlay(USER_CUSTOM_ICONS_DIR, CUSTOM_ICONS_DIR, `${iconName}.svg`);
  } else {
    file = path.join(ICONS_DIR, `${safeId(name)}.svg`);
  }
  if (!fs.existsSync(file)) {
    process.stderr.write(`[canva-killer] icon not found: "${name}"\n`);
    return '';
  }
  return fs.readFileSync(file, 'utf8').replace(/\s(?:width|height)="[^"]*"/g, '');
}

const SYSTEM_FONTS = new Set([
  'system-ui', 'sans-serif', 'serif', 'monospace', 'ui-monospace',
  'cursive', 'fantasy', 'inherit', 'initial', 'unset'
]);

function cleanFontName(fontFamily) {
  if (!fontFamily) return '';
  const m = fontFamily.match(/['"]([^'"]+)['"]/);
  const name = m ? m[1] : fontFamily.split(',')[0].trim();
  return SYSTEM_FONTS.has(name.toLowerCase()) ? '' : name;
}

// Fills {{token}} in the HTML from: palette + fonts + brand metadata + the post's `data`.
// `data` wins over the brand (allows per-post override). Content fields accept inline HTML
// (e.g. <span class="hl">word</span>) — the template's author controls the surface.
export function fillTemplate(html, brand, data = {}) {
  let googleFonts = brand.fonts.googleFonts;
  if (!googleFonts && (brand.fonts.display || brand.fonts.mono)) {
    const displayFamily = cleanFontName(brand.fonts.display);
    const monoFamily = cleanFontName(brand.fonts.mono);
    const families = [];
    if (displayFamily) families.push(`family=${encodeURIComponent(displayFamily)}:wght@400;500;600;700`);
    if (monoFamily) families.push(`family=${encodeURIComponent(monoFamily)}:wght@400;500;600;700`);
    if (families.length > 0) {
      googleFonts = `https://fonts.googleapis.com/css2?${families.join('&')}&display=swap`;
    }
  }

  const tokens = {
    ...brand.palette,
    display: brand.fonts.display,
    mono: brand.fonts.mono,
    googleFonts: googleFonts || '',
    logoText: brand.logoText,
    handle: brand.handle,
    name: brand.name,
    pixel: brand.fonts.pixel || brand.fonts.display, // optional pixel/retro font
    logoSvg: brand.logo ? resolveIcon(brand.logo, brand.id) : '', // inline wordmark (recolorable via currentColor)
    kicker: '', titulo: '', cta: '', topright: '',
    ...data,
    bgstyle: resolveBgStyle(data.bgimage), // wins over `data` above; never leaves the template with a raw bgstyle
    // background pattern class: data.pattern > brand.pattern > 'grid'
    patternClass: `pat-${data.pattern || brand.pattern || 'grid'}`,
    // overall pattern intensity dial (multiplies on top of each pattern's own opacity):
    // data.patternOpacity > brand.patternOpacity > 1 (fully visible, same as before this existed)
    patternOpacity: data.patternOpacity ?? brand.patternOpacity ?? 1,
    noiseUri: NOISE_URI,
  };
  const fillTokens = (s) => s.replace(/\{\{(\w+)\}\}/g, (_, k) => (tokens[k] != null ? String(tokens[k]) : ''));
  // base.css filled with the tokens (no icons) -> becomes the value of {{baseStyles}}
  tokens.baseStyles = fillTokens(fs.readFileSync(BASE_CSS, 'utf8'));
  // 1) icons: {{icon:shield}} (Lucide) or {{icon:custom/pirate}} (assets/custom) -> inline SVG
  html = html.replace(/\{\{icon:([\w/-]+)\}\}/g, (_, name) => resolveIcon(name, brand.id));
  // 2) simple tokens (includes {{baseStyles}})
  return fillTokens(html);
}

function launchBrowser() {
  return chromium.launch({ executablePath: CHROME, args: ['--no-sandbox'] });
}

// Renders ONE frame on a page of an already-open browser. Reused by render() (opens/closes
// the browser) and renderCarousel() (opens once for N slides).
async function renderInPage(browser, { brandId, templateId = 'post-square', data = {}, out }) {
  const brand = getBrand(brandId);
  const templateHtml = fs.readFileSync(resolveTemplatePath(templateId, brandId), 'utf8');
  const html = fillTemplate(templateHtml, brand, data);
  const outPath = out || path.join(DEFAULT_OUT_DIR, `${brandId}-${templateId}.png`);

  // Seed the viewport at #canvas's declared size up front (parsed the same way the studio does
  // it) — avoids a mid-render viewport resize for any template taller than the old fixed
  // 1080x1080 starting viewport (every story/9:16 template).
  const dimMatch = templateHtml.match(/width:\s*(\d+)px;\s*height:\s*(\d+)px/);
  const [startW, startH] = dimMatch ? [+dimMatch[1], +dimMatch[2]] : [1080, 1080];

  // deviceScaleFactor 2 => PNG @2x (crisp; social networks downsample it). BUT: headless
  // Chromium's screenshot has a real bug at 2x on tall pages (confirmed independent of clip vs
  // fullPage, and independent of any viewport resize) — output height around ~3800 device px
  // (i.e. any 9:16 story canvas, height 1920) grabs a wrapped/stale frame, visible as a sliver of
  // the bottom-of-page content ghosting in at y=0. Below that device-pixel height it's fine (a
  // 1080x1350 feed post at 2x = 2700 device px tested clean). Dropping to 1x for tall canvases
  // sidesteps it; 1080x1920 at 1x is already the native target resolution for a story anyway, so
  // nothing is actually lost.
  const dsf = startH * 2 > 3000 ? 1 : 2;
  const page = await browser.newPage({ viewport: { width: startW, height: startH }, deviceScaleFactor: dsf });
  try {
    await page.setContent(html, { waitUntil: 'networkidle' });
    await page.evaluate(() => document.fonts.ready); // wait for fonts to load
    const el = await page.$('#canvas');
    if (!el) throw new Error(`template "${templateId}" has no #canvas element`);
    // Capture via clip with the viewport sized to #canvas — avoids elementHandle.screenshot's
    // "wait for stable" (which hangs with certain content, e.g. inline SVG) and scroll stitching.
    const box = await el.boundingBox();
    const wantW = Math.ceil(box.x + box.width), wantH = Math.ceil(box.y + box.height);
    if (wantW !== startW || wantH !== startH) {
      // Fallback for a template whose real size didn't match the regex guess — still resize,
      // still settle a frame first (see note above for why).
      await page.setViewportSize({ width: wantW, height: wantH });
      await page.evaluate(() => new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(r))));
    }
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    await page.screenshot({ path: outPath, clip: box });
    return outPath;
  } finally {
    await page.close();
  }
}

// Renders one frame. Opens and closes the browser.
export async function render(opts) {
  const browser = await launchBrowser();
  try {
    return await renderInPage(browser, opts);
  } finally {
    await browser.close();
  }
}

// Renders an entire carousel in a SINGLE browser session. `slides` is an array of `data`
// objects (one per slide). Numbers {{slide}}/{{slidetotal}} automatically when the slide doesn't
// provide them. Returns the PNG paths in order (out/<prefix>-01.png, -02.png, ...).
export async function renderCarousel({ brandId, templateId = 'carrossel-slide', slides, outDir, prefix }) {
  if (!Array.isArray(slides) || slides.length === 0) {
    throw new Error('renderCarousel: `slides` must be a non-empty array');
  }
  const dir = outDir || DEFAULT_OUT_DIR;
  const pre = prefix || `${brandId}-carrossel`;
  const total = String(slides.length).padStart(2, '0');

  const browser = await launchBrowser();
  try {
    const paths = [];
    for (let i = 0; i < slides.length; i++) {
      const n = String(i + 1).padStart(2, '0');
      // automatic numbering first; whatever the slide brings (including slide/slidetotal) wins.
      const data = { slide: n, slidetotal: total, ...slides[i] };
      paths.push(await renderInPage(browser, { brandId, templateId, data, out: path.join(dir, `${pre}-${n}.png`) }));
    }
    return paths;
  } finally {
    await browser.close();
  }
}

// ---- CLI ----
function arg(name, def) { const i = process.argv.indexOf('--' + name); return i >= 0 ? process.argv[i + 1] : def; }
const isCli = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isCli) {
  const brandId = arg('brand', 'mybrand');
  const templateId = arg('template');
  const dataPath = arg('data');
  const out = arg('out');
  const parsed = dataPath ? JSON.parse(fs.readFileSync(dataPath, 'utf8')) : {};
  // --data with an array (or { slides: [...] }) => carousel; otherwise, a single frame.
  const slides = Array.isArray(parsed) ? parsed : parsed.slides;
  if (slides) {
    renderCarousel({ brandId, templateId: templateId || 'carrossel-slide', slides, outDir: arg('outdir'), prefix: arg('prefix') })
      .then(ps => console.log(`OK -> ${ps.length} slides:\n` + ps.join('\n')))
      .catch(e => { console.error('ERROR:', e.message); process.exit(1); });
  } else {
    render({ brandId, templateId: templateId || 'post-square', data: parsed, out })
      .then(p => console.log('OK ->', p))
      .catch(e => { console.error('ERROR:', e.message); process.exit(1); });
  }
}
